name: Parse

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  schedule:
    # every hour
    # - cron: "0 * * * *"
    # two times per day, in the morning at 7 and the evening at 19
    - cron: '0 7,19 * * *'

jobs:
  parse:
    name: Parsing
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up lts Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Clear Puppeteer cache
        shell: powershell
        run: |
          $cacheDir = "$env:USERPROFILE\.cache\puppeteer"
          if (Test-Path $cacheDir) {
            Remove-Item -Path $cacheDir -Recurse -Force
            Write-Output "Cleared cache at $cacheDir"
          }

      - name: Install Chromium
        shell: powershell
        run: |
          Write-Output "Installing Chrome..."
          npx puppeteer browsers install chrome@122
          Write-Output "Installation complete"
          $chromePath = "$env:USERPROFILE\.cache\puppeteer\chrome\win64-122.0.6261.57\chrome-win64\chrome.exe"
          Write-Output "Expected path: $chromePath"
          Write-Output "Path exists: $(Test-Path $chromePath)"
          if (Test-Path $chromePath) {
            Write-Output "Chrome found at: $chromePath"
            echo "CHROME_PATH=$chromePath" >> $env:GITHUB_ENV
          }

      - name: Run yarn script with envs
        run: yarn start
        env:
          DB_COLLECTION: ${{ secrets.DB_COLLECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          PARSE_URL: ${{ secrets.PARSE_URL }}
